"""add book price and image

Revision ID: 9474ed05f2ec
Revises: 3c53846f75d6
Create Date: 2020-12-05 15:32:03.293713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9474ed05f2ec'
down_revision = '3c53846f75d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('price_kopecks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('price_kopecks')
        batch_op.drop_column('picture_url')

    # ### end Alembic commands ###
